In [1]:
import os
import psycopg2
import pandas as pd

DATABASE_URL = 'postgres://qwosamqjhsmjse:bdc36cd41f29cad53b026230c202df7ff08f34b0a1ede8a6334f134cc146f45f@ec2-44-194-92-192.compute-1.amazonaws.com:5432/d79ilntrh62i11'
conn = psycopg2.connect(DATABASE_URL)
c = conn.cursor()

In [15]:
sql = '''
CREATE TABLE ITERATION (
    ID SERIAL NOT NULL,
    学習者 TEXT NOT NULL,
'''
for i in ["spade_", "club_", "dia_", "heart_"]:
    for j in range(1, 17):
        sql += f"    {i}{str(j).zfill(2)} INTEGER ,\n"

sql = sql[:-2] + ' );'
c.execute(sql)
conn.commit()

In [18]:
sql = "delete from iteration "
c.execute(sql)
conn.commit()

In [14]:
sql = "drop table iteration "
c.execute(sql)
conn.commit()

In [17]:
users = ['Shigeru', 'Ayako', 'Iroha', 'Kurumi', 'Satoru']
for user in users:
    sql = f"insert into iteration (学習者) values ('{user}') ;"
    c.execute(sql)

conn.commit()

In [5]:
sql = "select * from history"
pd.read_sql(sql, conn)

Empty DataFrame
Columns: [id, 学習者, 学習日, 再生回数]
Index: []

In [18]:
sql = "select * from iteration order by id "
pd.set_option("display.max_columns", None)
pd.read_sql(sql, conn)

,id,学習者,spade_01,spade_02,spade_03,spade_04,spade_05,spade_06,spade_07,spade_08,spade_09,spade_10,spade_11,spade_12,spade_13,spade_14,spade_15,spade_16,club_01,club_02,club_03,club_04,club_05,club_06,club_07,club_08,club_09,club_10,club_11,club_12,club_13,club_14,club_15,club_16,dia_01,dia_02,dia_03,dia_04,dia_05,dia_06,dia_07,dia_08,dia_09,dia_10,dia_11,dia_12,dia_13,dia_14,dia_15,dia_16,heart_01,heart_02,heart_03,heart_04,heart_05,heart_06,heart_07,heart_08,heart_09,heart_10,heart_11,heart_12,heart_13,heart_14,heart_15,heart_16
0,1,Shigeru,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,2,Ayako,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,3,Iroha,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,4,Kurumi,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,5,Satoru,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

True